# Generated by Django 6.0 on 2026-01-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilbarbearia',
            name='barbearia',
        ),
    ]
