# Generated by Django 6.0 on 2026-01-29 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_perfilbarbearia_barbearia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barbearia', to=settings.AUTH_USER_MODEL),
        ),
    ]
